export type ThemeConfig = {
  bg: string
  bgAlt: string
  text: string
  textMuted: string
  heading: string
  accent: string
  accentFg: string
  accentHover: string
  border: string
  card: string
  heroOverlay: string
  navScrolledBg: string
  inputBg: string
  inputBorder: string
  inputFocus: string
  successBg: string
  successText: string
  errorBg: string
  errorText: string
  reservationBg: string
  reservationIsDark: boolean
  footerBg: string
  footerText: string
  formButtonClass: string
}

export const themeConfigs: Record<string, ThemeConfig> = {
  'fine-dining': {
    bg: 'bg-[#0c0a09]',
    bgAlt: 'bg-[#141110]',
    text: 'text-stone-200',
    textMuted: 'text-stone-500',
    heading: 'font-serif',
    accent: 'bg-gradient-to-b from-amber-200 to-amber-400',
    accentFg: 'text-stone-950',
    accentHover: 'hover:brightness-105',
    border: 'border-stone-800/80',
    card: 'bg-stone-950/60',
    heroOverlay:
      'bg-gradient-to-b from-stone-950/95 via-stone-950/55 to-stone-950/85',
    navScrolledBg: 'bg-[#0c0a09]/92',
    inputBg: 'bg-stone-900/80',
    inputBorder: 'border-stone-700/80',
    inputFocus: 'focus:border-amber-400/80',
    successBg: 'bg-amber-500/10',
    successText: 'text-amber-200',
    errorBg: 'bg-red-950/40',
    errorText: 'text-red-300',
    reservationBg: 'bg-[#141110]',
    reservationIsDark: true,
    footerBg: 'bg-[#080706]',
    footerText: 'text-stone-500',
    formButtonClass: '!bg-gradient-to-b !from-amber-200 !to-amber-400 !text-stone-950 hover:!brightness-110',
  },
  'fast-food': {
    bg: 'bg-white',
    bgAlt: 'bg-amber-50',
    text: 'text-neutral-900',
    textMuted: 'text-neutral-600',
    heading: 'font-sans',
    accent: 'bg-red-600',
    accentFg: 'text-white',
    accentHover: 'hover:bg-red-700',
    border: 'border-neutral-200',
    card: 'bg-white',
    heroOverlay: 'bg-gradient-to-r from-red-950/90 via-orange-950/75 to-amber-950/65',
    navScrolledBg: 'bg-white/95',
    inputBg: 'bg-neutral-50',
    inputBorder: 'border-neutral-200',
    inputFocus: 'focus:border-red-500',
    successBg: 'bg-emerald-50',
    successText: 'text-emerald-800',
    errorBg: 'bg-red-50',
    errorText: 'text-red-700',
    reservationBg: 'bg-gradient-to-b from-neutral-900 via-red-950 to-neutral-950',
    reservationIsDark: true,
    footerBg: 'bg-red-600',
    footerText: 'text-amber-100',
    formButtonClass: '!bg-yellow-400 !text-neutral-900 !font-bold hover:!bg-yellow-300',
  },
  'traditional': {
    bg: 'bg-[#f3ece4]',
    bgAlt: 'bg-[#e8dfd4]',
    text: 'text-stone-800',
    textMuted: 'text-stone-600',
    heading: 'font-serif',
    accent: 'bg-[#9c4c34]',
    accentFg: 'text-[#fdf8f3]',
    accentHover: 'hover:bg-[#863d28]',
    border: 'border-stone-300/80',
    card: 'bg-[#faf6f0]/95',
    heroOverlay: 'bg-gradient-to-br from-stone-900/75 via-[#3f3429]/55 to-stone-900/25',
    navScrolledBg: 'bg-[#f3ece4]/95',
    inputBg: 'bg-[#faf6f0]',
    inputBorder: 'border-stone-300',
    inputFocus: 'focus:border-[#7c6a58]',
    successBg: 'bg-emerald-50/90',
    successText: 'text-emerald-900',
    errorBg: 'bg-red-50',
    errorText: 'text-red-800',
    reservationBg: 'bg-[#ebe3d8]',
    reservationIsDark: false,
    footerBg: 'bg-[#3f3429]',
    footerText: 'text-[#d4c4b0]',
    formButtonClass: '!bg-[#9c4c34] !text-[#fdf8f3] hover:!bg-[#863d28]',
  },
  'modern': {
    bg: 'bg-white',
    bgAlt: 'bg-slate-50',
    text: 'text-slate-900',
    textMuted: 'text-slate-500',
    heading: 'font-sans',
    accent: 'bg-orange-500',
    accentFg: 'text-white',
    accentHover: 'hover:bg-orange-600',
    border: 'border-slate-200/90',
    card: 'bg-white',
    heroOverlay: 'bg-gradient-to-br from-slate-950/90 via-slate-900/40 to-transparent',
    navScrolledBg: 'bg-white/90',
    inputBg: 'bg-white',
    inputBorder: 'border-slate-200',
    inputFocus: 'focus:border-orange-500',
    successBg: 'bg-emerald-50',
    successText: 'text-emerald-800',
    errorBg: 'bg-red-50',
    errorText: 'text-red-700',
    reservationBg: 'bg-gradient-to-b from-slate-100 to-white',
    reservationIsDark: false,
    footerBg: 'bg-slate-950',
    footerText: 'text-slate-400',
    formButtonClass: '!bg-orange-500 !text-white hover:!bg-orange-600',
  },
  'minimal': {
    bg: 'bg-white',
    bgAlt: 'bg-neutral-50',
    text: 'text-neutral-900',
    textMuted: 'text-neutral-500',
    heading: 'font-sans',
    accent: 'bg-neutral-900',
    accentFg: 'text-white',
    accentHover: 'hover:bg-neutral-800',
    border: 'border-neutral-200',
    card: 'bg-white',
    heroOverlay: 'bg-gradient-to-t from-black/50 via-black/20 to-transparent',
    navScrolledBg: 'bg-white/98',
    inputBg: 'bg-white',
    inputBorder: 'border-neutral-200',
    inputFocus: 'focus:border-neutral-900',
    successBg: 'bg-neutral-100',
    successText: 'text-neutral-900',
    errorBg: 'bg-red-50',
    errorText: 'text-red-700',
    reservationBg: 'bg-neutral-50',
    reservationIsDark: false,
    footerBg: 'bg-white',
    footerText: 'text-neutral-400',
    formButtonClass: '!bg-neutral-900 !text-white hover:!bg-neutral-800',
  },
  'lifestyle-cafe': {
    bg: 'bg-[#fef7f7]',
    bgAlt: 'bg-[#f5f0f0]',
    text: 'text-stone-800',
    textMuted: 'text-stone-500',
    heading: 'font-sans',
    accent: 'bg-rose-400',
    accentFg: 'text-white',
    accentHover: 'hover:bg-rose-500',
    border: 'border-rose-100',
    card: 'bg-white/90',
    heroOverlay: 'bg-gradient-to-t from-stone-900/55 via-rose-900/25 to-transparent',
    navScrolledBg: 'bg-[#fef7f7]/90',
    inputBg: 'bg-white',
    inputBorder: 'border-rose-100',
    inputFocus: 'focus:border-rose-400',
    successBg: 'bg-emerald-50',
    successText: 'text-emerald-800',
    errorBg: 'bg-red-50',
    errorText: 'text-red-700',
    reservationBg: 'bg-gradient-to-b from-[#fdf2f4] to-[#fef7f7]',
    reservationIsDark: false,
    footerBg: 'bg-[#2d2628]',
    footerText: 'text-rose-100/80',
    formButtonClass: '!bg-rose-400 !text-white hover:!bg-rose-500',
  },
}
